### ISSUE TITLE
建议增加个属性，处理导航栏遮挡问题

### ISSUE THREAD

**Issue by diors886** [chengp0819/MISFloatingBall#3]
如果有导航栏，并且我这个浮动球只需要显示在首页这个页面上，使用inSpecifiedView创建的话，可能会把球拖动到导航栏下面去；
建议可以增加一个edge属性，默认不能超过的区域是父view，如果设置了edge，父view边缘 + edge范围是不允许超过的，我感觉这样会更好

**Comment by wolfcolony** [comment]
恩，有道理，已经新增了一个方法可以通过 effectiveEdgeInsets 设置边距的
